# render.yaml
services:
  - type: web
    name: portfolio-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:geoinfo@localhost:5432/portfolio_db?client_encoding=utf8
      - key: SECRET_KEY
        value: mamakotiako12
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
